name: Terraform
on:
  push
jobs:
  terraform:
    name: 'Terraform'
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@master
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: 'Terraform Format'
      id: fmt
      run: terraform fmt -check
    - run: echo ${{ steps.fmt.outputs.stdout }}
    - run: echo ${{ steps.fmt.outputs.stderr }}
    - run: echo ${{ steps.fmt.outputs.exitcode }}
    - name: 'Terraform Init'
      id: init
      run: terraform init
    - run: echo ${{ steps.init.outputs.stdout }}
    - run: echo ${{ steps.init.outputs.stderr }}
    - run: echo ${{ steps.init.outputs.exitcode }}
    - name: 'Terraform Validate'
      id: validate
      run: terraform validate
    - run: echo ${{ steps.validate.outputs.stdout }}
    - run: echo ${{ steps.validate.outputs.stderr }}
    - run: echo ${{ steps.validate.outputs.exitcode }}
    - name: 'Terraform Plan'
      id: plan
      run: terraform plan
    - run: echo ${{ steps.plan.outputs.stdout }}
    - run: echo ${{ steps.plan.outputs.stderr }}
    - run: echo ${{ steps.plan.outputs.exitcode }}